name: Main workflow
on:
  push: {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.4
          - snapshot
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-keg@master

      - name: Run tests
        if: matrix.allow_failure != true
        run: 'make test'

      - name: Run tests (allow failure)
        if: matrix.allow_failure == true
        run: 'make test || true'
